<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
		<form  method='post'>
		<label style='padding-left: 10px;' for='event'>Name:</label><input type='text' name='event'><br>
		<label style='padding-left: 10px;' for='date'>Date:</label><input type='date' name='date'><br>
		<label style='padding-left: 10px;' for='name'>Creator:</label><input type='text' name='name'><br>
		<input type="text" name="itemName" placeholder="Item Name">
    	<input type="number" name="quantity" value="1" min="1" placeholder="Quantity">
		<button style='margin-left: 10px;'>Add</button></form>
</body>
</html>